version: '3.8'

services:
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: ./dev.env
    ports:
      - 8000:8000
    command: gunicorn products_aggregator_project.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: dev_db
    env_file: ./dev.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
